from __future__ import annotations

from puripuly_heart.app.ports.application_runtime_shutdown import (
    ApplicationRuntimeShutdownPort,
)
from puripuly_heart.app.services.application_shutdown import (
    ApplicationShutdownCallback,
    application_shutdown_callback,
)
from puripuly_heart.core.lifecycle import (
    SHUTDOWN_PHASE_CLOSE_LOGGING_DIAGNOSTICS,
    SHUTDOWN_PHASE_CLOSE_PROVIDERS_OUTPUT_ADAPTERS,
    SHUTDOWN_PHASE_FINAL_DIAGNOSTICS,
    SHUTDOWN_PHASE_FREEZE_INGRESS,
    SHUTDOWN_PHASE_OWNER_DRAIN_CANCEL,
    SHUTDOWN_PHASE_STOP_EXTERNAL_PRODUCERS,
)


async def _close_managed_gemma_if_available(runtime: object) -> None:
    callback = getattr(runtime, "close_managed_gemma_runtime", None)
    if callable(callback):
        await callback()


def compose_application_runtime_shutdown_callbacks(
    runtime: ApplicationRuntimeShutdownPort,
) -> tuple[ApplicationShutdownCallback, ...]:
    return (
        application_shutdown_callback(
            phase=SHUTDOWN_PHASE_FREEZE_INGRESS,
            owner_name="ApplicationRuntime",
            callback_name="freeze_ingress",
            callback=runtime.freeze_application_ingress,
        ),
        application_shutdown_callback(
            phase=SHUTDOWN_PHASE_FREEZE_INGRESS,
            owner_name="GithubStarPromptOwner",
            callback_name="stop_ingress",
            callback=runtime.stop_github_star_prompt_ingress,
        ),
        application_shutdown_callback(
            phase=SHUTDOWN_PHASE_STOP_EXTERNAL_PRODUCERS,
            owner_name="ManualTypingOwner",
            callback_name="release",
            callback=runtime.release_manual_typing,
        ),
        application_shutdown_callback(
            phase=SHUTDOWN_PHASE_STOP_EXTERNAL_PRODUCERS,
            owner_name="ClipboardRuntime",
            callback_name="close",
            callback=runtime.close_clipboard_runtime,
        ),
        application_shutdown_callback(
            phase=SHUTDOWN_PHASE_STOP_EXTERNAL_PRODUCERS,
            owner_name="VrchatOscPresenceProbeOwner",
            callback_name="cancel",
            callback=runtime.cancel_vrchat_osc_presence_probe,
        ),
        application_shutdown_callback(
            phase=SHUTDOWN_PHASE_OWNER_DRAIN_CANCEL,
            owner_name="SelfCaptureSessionOwner",
            callback_name="stop_ingress",
            callback=runtime.stop_self_capture_ingress,
        ),
        application_shutdown_callback(
            phase=SHUTDOWN_PHASE_OWNER_DRAIN_CANCEL,
            owner_name="VrcMicReceiverRuntime",
            callback_name="close",
            callback=runtime.close_vrc_mic_receiver_runtime,
        ),
        application_shutdown_callback(
            phase=SHUTDOWN_PHASE_OWNER_DRAIN_CANCEL,
            owner_name="OverlayApplicationOwner",
            callback_name="close",
            callback=runtime.close_overlay_runtime,
        ),
        application_shutdown_callback(
            phase=SHUTDOWN_PHASE_OWNER_DRAIN_CANCEL,
            owner_name="PeerApplicationOwner",
            callback_name="close",
            callback=runtime.close_peer_runtime,
        ),
        application_shutdown_callback(
            phase=SHUTDOWN_PHASE_STOP_EXTERNAL_PRODUCERS,
            owner_name="GithubStarPromptOwner",
            callback_name="close",
            callback=runtime.close_github_star_prompt_owner,
        ),
        application_shutdown_callback(
            phase=SHUTDOWN_PHASE_STOP_EXTERNAL_PRODUCERS,
            owner_name="OpenRouterPkceFlowOwner",
            callback_name="close",
            callback=runtime.close_openrouter_oauth_runtime,
        ),
        application_shutdown_callback(
            phase=SHUTDOWN_PHASE_OWNER_DRAIN_CANCEL,
            owner_name="LocalASRProvisioningRuntime",
            callback_name="close",
            callback=runtime.close_local_asr_provisioning,
        ),
        application_shutdown_callback(
            phase=SHUTDOWN_PHASE_OWNER_DRAIN_CANCEL,
            owner_name="MicrophoneTestSessionOwner",
            callback_name="close",
            callback=runtime.close_microphone_test_runtime,
        ),
        application_shutdown_callback(
            phase=SHUTDOWN_PHASE_OWNER_DRAIN_CANCEL,
            owner_name="SelfCaptureSessionOwner",
            callback_name="close",
            callback=runtime.close_self_capture_owner,
        ),
        application_shutdown_callback(
            phase=SHUTDOWN_PHASE_OWNER_DRAIN_CANCEL,
            owner_name="PeerCaptureSessionOwner",
            callback_name="close",
            callback=runtime.close_peer_capture_owner,
        ),
        application_shutdown_callback(
            phase=SHUTDOWN_PHASE_OWNER_DRAIN_CANCEL,
            owner_name="ApplicationRuntimeLoggingOwner",
            callback_name="close_background_tasks",
            callback=runtime.close_runtime_logging_background_tasks,
        ),
        application_shutdown_callback(
            phase=SHUTDOWN_PHASE_OWNER_DRAIN_CANCEL,
            owner_name="ManagedAuthOwner",
            callback_name="close",
            callback=runtime.close_managed_auth_owner,
        ),
        application_shutdown_callback(
            phase=SHUTDOWN_PHASE_OWNER_DRAIN_CANCEL,
            owner_name="TranslationEnableOwner",
            callback_name="close",
            callback=runtime.close_translation_enable_owner,
        ),
        application_shutdown_callback(
            phase=SHUTDOWN_PHASE_OWNER_DRAIN_CANCEL,
            owner_name="ManagedUsageOwner",
            callback_name="close",
            callback=runtime.close_managed_usage_owner,
        ),
        application_shutdown_callback(
            phase=SHUTDOWN_PHASE_CLOSE_PROVIDERS_OUTPUT_ADAPTERS,
            owner_name="RuntimePipelineLauncher",
            callback_name="close_failed_resources",
            callback=runtime.close_runtime_pipeline_launcher,
        ),
        application_shutdown_callback(
            phase=SHUTDOWN_PHASE_CLOSE_PROVIDERS_OUTPUT_ADAPTERS,
            owner_name="SelfTranslationIngress",
            callback_name="close",
            callback=runtime.close_self_translation_ingress,
        ),
        application_shutdown_callback(
            phase=SHUTDOWN_PHASE_CLOSE_PROVIDERS_OUTPUT_ADAPTERS,
            owner_name="PeerTranslationIngress",
            callback_name="close",
            callback=runtime.close_peer_translation_ingress,
        ),
        application_shutdown_callback(
            phase=SHUTDOWN_PHASE_CLOSE_PROVIDERS_OUTPUT_ADAPTERS,
            owner_name="TranslationTurnLifecycleOwner",
            callback_name="close",
            callback=runtime.close_translation_turns,
        ),
        application_shutdown_callback(
            phase=SHUTDOWN_PHASE_CLOSE_PROVIDERS_OUTPUT_ADAPTERS,
            owner_name="OutputRuntime",
            callback_name="close",
            callback=runtime.close_output_runtime,
        ),
        application_shutdown_callback(
            phase=SHUTDOWN_PHASE_CLOSE_PROVIDERS_OUTPUT_ADAPTERS,
            owner_name="SelfChannelRuntime",
            callback_name="close",
            callback=runtime.close_self_channel_runtime,
        ),
        application_shutdown_callback(
            phase=SHUTDOWN_PHASE_CLOSE_PROVIDERS_OUTPUT_ADAPTERS,
            owner_name="PeerChannelRuntime",
            callback_name="close",
            callback=runtime.close_peer_channel_runtime,
        ),
        application_shutdown_callback(
            phase=SHUTDOWN_PHASE_CLOSE_PROVIDERS_OUTPUT_ADAPTERS,
            owner_name="LocalASRProviderRuntimeOwner",
            callback_name="close",
            callback=runtime.close_local_asr_runtime,
        ),
        application_shutdown_callback(
            phase=SHUTDOWN_PHASE_CLOSE_PROVIDERS_OUTPUT_ADAPTERS,
            owner_name="ProviderRuntimeHandle:llm",
            callback_name="close",
            callback=runtime.close_llm_runtime,
        ),
        application_shutdown_callback(
            phase=SHUTDOWN_PHASE_CLOSE_PROVIDERS_OUTPUT_ADAPTERS,
            owner_name="ManagedGemmaTranslationOwner",
            callback_name="close",
            callback=lambda: _close_managed_gemma_if_available(runtime),
        ),
        application_shutdown_callback(
            phase=SHUTDOWN_PHASE_CLOSE_PROVIDERS_OUTPUT_ADAPTERS,
            owner_name="VrchatOscUdpSender",
            callback_name="close",
            callback=runtime.close_vrchat_sender,
        ),
        application_shutdown_callback(
            phase=SHUTDOWN_PHASE_CLOSE_PROVIDERS_OUTPUT_ADAPTERS,
            owner_name="ManagedOpenRouterReleaseService",
            callback_name="close",
            callback=runtime.close_managed_openrouter_release_service,
        ),
        ApplicationShutdownCallback(
            phase=SHUTDOWN_PHASE_FINAL_DIAGNOSTICS,
            owner_name="ApplicationRuntime",
            callback_name="emit_final_shutdown_diagnostics",
            callback=runtime.emit_final_application_shutdown_diagnostics,
        ),
        ApplicationShutdownCallback(
            phase=SHUTDOWN_PHASE_CLOSE_LOGGING_DIAGNOSTICS,
            owner_name="RuntimeLoggingService",
            callback_name="close_after_producers_stop",
            callback=runtime.close_runtime_logging,
        ),
    )
