from __future__ import annotations

from typing import Protocol

from puripuly_heart.app.services.application_shutdown import (
    ApplicationShutdownContext,
    ApplicationShutdownDiagnostic,
)


class ApplicationRuntimeShutdownPort(Protocol):
    def effective_osc_ports(self) -> tuple[int | None, int | None]: ...

    def freeze_application_ingress(self) -> None: ...

    def stop_github_star_prompt_ingress(self) -> None: ...

    async def release_manual_typing(self) -> None: ...

    async def close_clipboard_runtime(self) -> None: ...

    async def cancel_vrchat_osc_presence_probe(self) -> None: ...

    async def stop_self_capture_ingress(self) -> None: ...

    async def close_vrc_mic_receiver_runtime(self) -> None: ...

    async def close_overlay_runtime(self) -> None: ...

    async def close_peer_runtime(self) -> None: ...

    async def close_github_star_prompt_owner(self) -> None: ...

    async def close_openrouter_oauth_runtime(self) -> None: ...

    async def close_local_asr_provisioning(self) -> None: ...

    async def close_microphone_test_runtime(self) -> None: ...

    async def close_self_capture_owner(self) -> None: ...

    async def close_runtime_logging_background_tasks(self) -> None: ...

    async def close_managed_auth_owner(self) -> None: ...

    async def close_translation_enable_owner(self) -> None: ...

    async def close_managed_usage_owner(self) -> None: ...

    async def close_runtime_pipeline_launcher(self) -> None: ...

    async def close_peer_capture_owner(self) -> None: ...

    async def close_self_translation_ingress(self) -> None: ...

    async def close_peer_translation_ingress(self) -> None: ...

    async def close_translation_turns(self) -> None: ...

    async def close_output_runtime(self) -> None: ...

    async def close_self_channel_runtime(self) -> None: ...

    async def close_peer_channel_runtime(self) -> None: ...

    async def close_local_asr_runtime(self) -> None: ...

    async def close_llm_runtime(self) -> None: ...

    async def close_managed_gemma_runtime(self) -> None: ...

    def close_vrchat_sender(self) -> None: ...

    async def close_managed_openrouter_release_service(self) -> None: ...

    def emit_final_application_shutdown_diagnostics(
        self,
        context: ApplicationShutdownContext,
    ) -> None: ...

    def close_runtime_logging(
        self,
        context: ApplicationShutdownContext,
    ) -> None: ...

    def emit_application_shutdown_diagnostic(
        self,
        diagnostic: ApplicationShutdownDiagnostic,
    ) -> None: ...
