from __future__ import annotations

import logging
from collections.abc import Awaitable, Callable, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Protocol

from puripuly_heart.app.language_selection import LanguageSelectionChange
from puripuly_heart.app.ports.ui_models import (
    GpuNoticeAction,
    ManagedGemmaNoticeAction,
    OverlayPeerPresentationState,
)
from puripuly_heart.app.ports.ui_presentation import UiPresentationPort
from puripuly_heart.app.ports.vrchat_osc_presence import VrchatOscPresencePort
from puripuly_heart.app.services.application_shutdown import (
    ApplicationShutdownCallback,
    ApplicationShutdownCoordinator,
    ApplicationShutdownDiagnostic,
)


@dataclass(frozen=True, slots=True)
class UiApplicationState:
    config_path: Path
    runtime_logging_mode: str
    translation_enabled: bool
    stt_state: object | None
    peer_translation_eula_accepted: bool | None
    microphone_test_active: bool
    provider_name: str | None
    overlay_target: str | None
    desktop_overlay_captions_locked: bool
    managed_auth_referral_bonus_applied: bool
    translation_runtime_ready: bool | None = None


class UiApplicationFactoryPort(Protocol):
    def __call__(
        self,
        *,
        presentation: UiPresentationPort,
        config_path: Path,
        allow_stable_settings_import: bool = False,
        runtime_logging_sinks: object | None = None,
        vrchat_osc_presence: VrchatOscPresencePort | None = None,
    ) -> UiApplicationPort: ...


class UiApplicationPort(Protocol):
    def state(self) -> UiApplicationState: ...

    def effective_osc_ports(self) -> tuple[int | None, int | None]: ...

    def http_extension_registry(self) -> object | None: ...

    def compatibility_settings(self) -> Any | None: ...

    @property
    def overlay_calibration(self) -> object | None: ...

    async def start(self) -> None: ...

    async def stop(self) -> None: ...

    def application_lifecycle(self) -> ApplicationShutdownCoordinator: ...

    def register_application_shutdown_callbacks(
        self,
        callbacks: Sequence[ApplicationShutdownCallback],
    ) -> None: ...

    def emit_application_shutdown_diagnostic(
        self,
        diagnostic: ApplicationShutdownDiagnostic,
    ) -> Awaitable[None] | None: ...

    def log_basic(self, message: str, *, level: int = logging.INFO) -> None: ...

    def log_detailed(self, message: str, *, level: int = logging.INFO) -> None: ...

    async def submit_text(self, text: str) -> None: ...

    def set_manual_input_activity(self, has_text: bool) -> None: ...

    async def set_translation_enabled(self, enabled: bool) -> object: ...

    async def set_stt_enabled(self, enabled: bool) -> object: ...

    async def set_peer_translation_enabled(self, enabled: bool) -> object: ...

    async def set_overlay_enabled(self, enabled: bool) -> object: ...

    async def retry_peer_process_capture(self) -> bool: ...

    async def apply_loopback_capture_option(self, value: str) -> None: ...

    def list_loopback_capture_options(self) -> object: ...

    def list_loopback_process_options(self) -> object: ...

    def list_loopback_device_options(self) -> object: ...

    def current_loopback_capture_option_value(self) -> object: ...

    def loopback_capture_summary(self) -> object: ...

    async def on_dashboard_language_change(
        self,
        change: LanguageSelectionChange,
    ) -> None: ...

    def capture_settings_view_change(self, settings: Any) -> object: ...

    def merge_settings_view_change_with_current(self, captured: object) -> Any: ...

    def refresh_settings_projection(
        self,
        *,
        preserve_custom_vocab_draft: bool = False,
    ) -> bool: ...

    def refresh_settings_after_openrouter_pkce_success(self) -> bool: ...

    def merge_settings_tab_apply_with_current_languages(self, settings: Any) -> Any: ...

    async def apply_settings(self, settings: Any) -> object: ...

    async def apply_providers(
        self,
        settings: Any | None = None,
        *,
        force_rebuild_llm: bool = False,
        persist_settings: bool = True,
        refresh_ui: bool = True,
    ) -> object: ...

    async def install_selected_gpu_model_if_needed(self) -> None: ...

    async def ensure_gpu_device_discovery(self) -> None: ...

    async def start_microphone_test(
        self,
        *,
        meter_callback: Callable[[float], None] | None = None,
    ) -> bool: ...

    async def stop_microphone_test(self) -> None: ...

    def set_runtime_logging_mode(self, mode: str) -> str: ...

    async def set_desktop_overlay_captions_locked(self, locked: bool) -> None: ...

    async def set_desktop_overlay_size_preset(self, size_preset: str) -> None: ...

    async def reset_desktop_overlay_position(self) -> None: ...

    def begin_overlay_calibration(self) -> object: ...

    def set_overlay_calibration_field(self, *args: Any, **kwargs: Any) -> object: ...

    def apply_overlay_calibration(self) -> object: ...

    def cancel_overlay_calibration(self) -> object: ...

    def overlay_peer_presentation_state(self) -> OverlayPeerPresentationState | None: ...

    def dashboard_managed_auth_action(self) -> str: ...

    def dashboard_managed_auth_prompt_kind(self) -> str: ...

    async def apply_telemetry_consent(self, consent: str) -> Any | None: ...

    async def accept_peer_translation_eula_and_enable(self) -> object: ...

    def local_llm_selected(self) -> bool: ...

    async def connect_openrouter_via_pkce(
        self,
        *,
        target_settings: Any,
        launch_source: str,
    ) -> bool: ...

    def reopen_openrouter_pkce_authorization_url(self) -> None: ...

    def build_managed_openrouter_byok_target_settings(self) -> Any | None: ...

    async def verify_api_key(self, provider: str, key: str) -> tuple[bool, str]: ...

    def persist_api_key_verification(
        self,
        provider: str,
        key: str,
        success: bool,
    ) -> None: ...

    async def persist_provider_secret_change(self, key: str, value: str) -> bool: ...

    def clear_provider_verification(self, provider: str) -> None: ...

    async def start_qq_managed_auth_from_dialog(self, **kwargs: Any) -> object: ...

    async def start_discord_managed_auth_from_dialog(self, **kwargs: Any) -> object: ...

    def reopen_discord_managed_auth_browser(self) -> object: ...

    def supports_discord_managed_auth_reopen(self) -> bool: ...

    def cancel_discord_managed_auth(self) -> object: ...

    def translation_enable_succeeded(self, result: object) -> bool: ...

    def clear_managed_auth_pending_state(self) -> None: ...

    def get_event_language_codes(self) -> tuple[str | None, str | None]: ...

    def schedule_github_star_prompt_translation_success_observed(self) -> None: ...

    async def record_telemetry_translation_success_day(self) -> None: ...

    def should_show_github_star_prompt(self) -> bool: ...

    async def persist_github_star_prompt_eligible_launch(self) -> bool: ...

    async def refresh_openrouter_usage_after_launch(self) -> bool: ...

    async def prepare_runtime_after_launch(self) -> None: ...

    async def check_for_update(self) -> object | None: ...

    def start_github_star_prompt(
        self,
        run_prompt: Callable[[int], Awaitable[bool]],
    ) -> Awaitable[bool]: ...

    def is_current_github_star_prompt_generation(self, generation: int) -> bool: ...

    def stop_github_star_prompt_ingress(self) -> None: ...

    async def close_github_star_prompt_runtime(self) -> None: ...

    def start_managed_auth_task(
        self,
        *,
        task_runner: Callable[[Callable[[], Awaitable[Any]]], object],
        task_factory: Callable[[], Awaitable[Any]],
        task_name: str,
        generation: int,
    ) -> object: ...

    def clear_managed_auth_task(self, task_name: str) -> None: ...

    def cancel_managed_auth_task(
        self,
        handle: object | None,
        *,
        task_name: str,
    ) -> None: ...

    def managed_auth_task_names(self) -> tuple[str, ...]: ...

    def managed_auth_tasks_open(self) -> bool: ...

    async def close_managed_auth_tasks(self) -> None: ...

    async def persist_github_star_prompt_opened(
        self,
        *,
        should_open: Callable[[], bool] | None = None,
    ) -> bool: ...

    async def persist_github_star_prompt_clicked(self) -> None: ...

    def cycle_debug_capture_fault_profile(self) -> str: ...

    def cycle_debug_stt_fault_profile(self) -> str: ...

    def clear_debug_audio_fault_profiles(self) -> None: ...

    def handle_gpu_notice_action(self, action: GpuNoticeAction) -> object: ...

    async def handle_managed_gemma_notice_action(
        self,
        action: ManagedGemmaNoticeAction,
    ) -> object: ...


__all__ = ["UiApplicationPort", "UiApplicationState"]
